import 'package:flutter/cupertino.dart';

import '../model/product.dart';

class ProductsProvider with ChangeNotifier {
  List<Product> get getProducts {
    return _productsList;
  }

  List<Product> get getOnSaleProducts {
    return _productsList.where((element) => element.isOnSale).toList();
  }

  List<Product> getProdsByCat(int categoryId) {
    return _productsList.where((element) => element.categoryId == categoryId).toList();
  }

  Product getProdById(int id) {
    return _productsList.firstWhere((element) => element.id == id);
  }

  static final List<Product> _productsList = [
    Product(
      id: 1,
      name: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      image: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      categoryId: 1,
      isOnSale: true,
      isPiece: false,
    ),
    Product(
      id: 2,
      name: 'Avocado',
      price: 0.88,
      salePrice: 0.5,
      image: 'https://i.ibb.co/9VKXw5L/Avocat.png',
      categoryId: 1,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 3,
      name: 'Black grapes',
      price: 1.22,
      salePrice: 0.7,
      image: 'https://i.ibb.co/c6w5zrC/Black-Grapes-PNG-Photos.png',
      categoryId: 1,
      isOnSale: true,
      isPiece: false,
    ),
    Product(
      id: 4,
      name: 'Fresh green grape',
      price: 1.5,
      salePrice: 0.5,
      image: 'https://i.ibb.co/HKx2bsp/Fresh-green-grape.png',
      categoryId: 4,
      isOnSale: true,
      isPiece: false,
    ),
    Product(
      id: 5,
      name: 'Green grape',
      price: 0.99,
      salePrice: 0.4,
      image: 'https://i.ibb.co/bHKtc33/grape-green.png',
      categoryId: 1,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 6,
      name: 'Red apple',
      price: 0.6,
      salePrice: 0.2,
      image: 'https://i.ibb.co/crwwSG2/red-apple.png',
      categoryId: 1,
      isOnSale: true,
      isPiece: false,
    ),
    // Vegi
    Product(
      id: 7,
      name: 'Carottes',
      price: 0.99,
      salePrice: 0.5,
      image: 'https://i.ibb.co/TRbNL3c/Carottes.png',
      categoryId: 2,
      isOnSale: true,
      isPiece: false,
    ),
    Product(
      id: 8,
      name: 'Cauliflower',
      price: 1.99,
      salePrice: 0.99,
      image: 'https://i.ibb.co/xGWf2rH/Cauliflower.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 9,
      name: 'Cucumber',
      price: 0.99,
      salePrice: 0.5,
      image: 'https://i.ibb.co/kDL5GKg/cucumbers.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 10,
      name: 'Jalape',
      price: 1.99,
      salePrice: 0.89,
      image: 'https://i.ibb.co/Dtk1YP8/Jalape-o.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 11,
      name: 'Long yam',
      price: 2.99,
      salePrice: 1.59,
      image: 'https://i.ibb.co/V3MbcST/Long-yam.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 12,
      name: 'Onions',
      price: 0.59,
      salePrice: 0.28,
      image: 'https://i.ibb.co/GFvm1Zd/Onions.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 13,
      name: 'Plantain-flower',
      price: 0.99,
      salePrice: 0.389,
      image: 'https://i.ibb.co/RBdq0PD/Plantain-flower.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 14,
      name: 'Potato',
      price: 0.99,
      salePrice: 0.59,
      image: 'https://i.ibb.co/wRgtW55/Potato.png',
      categoryId: 2,
      isOnSale: true,
      isPiece: false,
    ),
    Product(
      id: 15,
      name: 'Radish',
      price: 0.99,
      salePrice: 0.79,
      image: 'https://i.ibb.co/YcN4ZsD/Radish.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 16,
      name: 'Red peppers',
      price: 0.99,
      salePrice: 0.57,
      image: 'https://i.ibb.co/JthGdkh/Red-peppers.png',
      categoryId: 2,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 17,
      name: 'Squash',
      price: 3.99,
      salePrice: 2.99,
      image: 'https://i.ibb.co/p1V8sq9/Squash.png',
      categoryId: 2,
      isOnSale: true,
      isPiece: true,
    ),
    Product(
      id: 18,
      name: 'Tomatoes',
      price: 0.99,
      salePrice: 0.39,
      image: 'https://i.ibb.co/PcP9xfK/Tomatoes.png',
      categoryId: 2,
      isOnSale: true,
      isPiece: false,
    ),
    // Grains
    Product(
      id: 19,
      name: 'Corn-cobs',
      price: 0.29,
      salePrice: 0.19,
      image: 'https://i.ibb.co/8PhwVYZ/corn-cobs.png',
      categoryId: 6,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 20,
      name: 'Peas',
      price: 0.99,
      salePrice: 0.49,
      image: 'https://i.ibb.co/7GHM7Dp/peas.png',
      categoryId: 6,
      isOnSale: false,
      isPiece: false,
    ),
    // Herbs
    Product(
      id: 21,
      name: 'Asparagus',
      price: 6.99,
      salePrice: 4.99,
      image: 'https://i.ibb.co/RYRvx3W/Asparagus.png',
      categoryId: 6,
      isOnSale: false,
      isPiece: false,
    ),
    Product(
      id: 22,
      name: 'Brokoli',
      price: 0.99,
      salePrice: 0.89,
      image: 'https://i.ibb.co/KXTtrYB/Brokoli.png',
      categoryId: 6,
      isOnSale: true,
      isPiece: true,
    ),
    Product(
      id: 23,
      name: 'Buk-choy',
      price: 1.99,
      salePrice: 0.99,
      image: 'https://i.ibb.co/MNDxNnm/Buk-choy.png',
      categoryId: 6,
      isOnSale: true,
      isPiece: true,
    ),
    Product(
      id: 24,
      name: 'Chinese-cabbage-wombok',
      price: 0.99,
      salePrice: 0.5,
      image: 'https://i.ibb.co/7yzjHVy/Chinese-cabbage-wombok.png',
      categoryId: 6,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 25,
      name: 'Kangkong',
      price: 0.99,
      salePrice: 0.5,
      image: 'https://i.ibb.co/HDSrR2Y/Kangkong.png',
      categoryId: 6,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 26,
      name: 'Leek',
      price: 0.99,
      salePrice: 0.5,
      image: 'https://i.ibb.co/Pwhqkh6/Leek.png',
      categoryId: 6,
      isOnSale: false,
      isPiece: true,
    ),
    Product(
      id: 27,
      name: 'Spinach',
      price: 0.89,
      salePrice: 0.59,
      image: 'https://i.ibb.co/bbjvgcD/Spinach.png',
      categoryId: 6,
      isOnSale: true,
      isPiece: true,
    ),
    Product(
      id: 28,
      name: 'Almond',
      price: 8.99,
      salePrice: 6.5,
      image: 'https://i.ibb.co/c8QtSr2/almand.jpg',
      categoryId: 6,
      isOnSale: true,
      isPiece: false,
    ),
  ];
}
